import { Injectable } from '@angular/core';
import { of, timer } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable({
    providedIn: 'root',
})
export class PerformanceService {
    constructor() { }
    getData() {
        return {
            obj1: obj1,
            obj2: obj2,
        };
    }
}
export type Obj2Type = {
    bEdvTyp: string;
    bKzLackMaterial: string;
    dZEArbeitsWert: number;
    dPreis: number;
    dZeVs5: number;
    bVs5Cha: boolean;
    lMaterialEinheiten: number;
    childrenCheckbox?: boolean;
};
export type obj1Type = {
    Disabled: boolean;
    Group: any;
    Selected: boolean;
    Text: string;
    Value: string;
};

export const obj1:obj1Type[] = [
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Freier Typ',
        Value: '**',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '00TEST-MODELL',
        Value: '00',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Typ1',
        Value: '01',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'TYP 2<79',
        Value: '02',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'TYP 3',
        Value: '03',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'VW 411',
        Value: '04',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'VW K70',
        Value: '05',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PASSAT MODELL <80',
        Value: '06',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Golf/Jetta>74',
        Value: '08',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'POLO DERBY<81',
        Value: '09',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "LT '83->'96",
        Value: '10',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "TRANSPORTER '80->'90",
        Value: '11',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'ILTIS',
        Value: '12',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "SCIROCCO '84->'92",
        Value: '13',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PASSAT/SANTANA '81->",
        Value: '14',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 80/90 '79->'87/",
        Value: '15',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AUDI QUATTRO',
        Value: '16',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'POLO/DERBY/POLO COUP',
        Value: '17',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "GOLF/JETTA '83->'88",
        Value: '18',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Caddy>78',
        Value: '19',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'POLO 02<09',
        Value: '1A',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "GOLF  PLUS '05->",
        Value: '1B',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PASSAT/VARIANT '06->",
        Value: '1C',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PASSAT/VARIANT '01->",
        Value: '1D',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Sharan 04>11',
        Value: '1E',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "NEW BEETLE '98->",
        Value: '1F',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "EOS '06->",
        Value: '1G',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Tiguan >08',
        Value: '1H',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Passat CC>09/CC>10',
        Value: '1I',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Scirocco>09',
        Value: '1J',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Golf 09<13',
        Value: '1K',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Polo>09',
        Value: '1L',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Touareg>11',
        Value: '1M',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: '1N',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Sharan>11',
        Value: '1O',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Passat/Variant',
        Value: '1P',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: '1Q',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: '1R',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'UP MOD. 12 >',
        Value: '1S',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GOLF >13',
        Value: '1T',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Golf 14 -->',
        Value: '1V',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Routan>08',
        Value: '1X',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 80/90 '87->'91/",
        Value: '20',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PASSAT '88->'97",
        Value: '21',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "CORRADO '89->'95",
        Value: '22',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "TARO '89->'97",
        Value: '23',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "TRANSPORTER '91->'03",
        Value: '24',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 100 '91->'94/A6",
        Value: '25',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Golf/Vento 92>99 Var',
        Value: '26',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 80/COUPE '92->9",
        Value: '27',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI CABRIOLET '92->",
        Value: '28',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "GOLF CABRIOLET '94->",
        Value: '29',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A6 '05->/AVANT ",
        Value: '2A',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI Q7 '07->",
        Value: '2B',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A4 05->/AVANT '",
        Value: '2C',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A4 CABRIO '07->",
        Value: '2D',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI TT COUPE '07->/",
        Value: '2E',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AUR8>/Spyder',
        Value: '2F',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AUDI A5 >08',
        Value: '2G',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Audi A4 >08Avant 08',
        Value: '2H',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AAUA Cabrio>08',
        Value: '2I',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AUA5 Cabrio>10',
        Value: '2J',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Audi Q5>09',
        Value: '2K',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Audi A8 >10',
        Value: '2L',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: '2M',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Audi A7>11',
        Value: '2N',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Audi A6>11',
        Value: '2O',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: '2P',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: '2Q',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI V8 '89->'94",
        Value: '30',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A8 '94->'02",
        Value: '31',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "POLO '95->'02",
        Value: '32',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A4 '95->'00/AVA",
        Value: '33',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "L 80 '95->",
        Value: '34',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "SHARAN '96->'03",
        Value: '35',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Caddy Mod. 96>',
        Value: '36',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "POLO CLASSIC '96->'0",
        Value: '37',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A3 '97->'03",
        Value: '38',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "CADDY PICKUP '97->'0",
        Value: '39',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "CRAFTER KOMBI '06->",
        Value: '3A',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "CRAFTER KASTEN '06->",
        Value: '3B',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'CRAFTER PRITSCHE/DOK',
        Value: '3C',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Amarok>10',
        Value: '3D',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GTC>07',
        Value: '3E',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "LT '97->",
        Value: '40',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PASSAT/VARIANT '97->",
        Value: '41',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A6/AVANT '98->'",
        Value: '42',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "GOLF '98->'03/VARIAN",
        Value: '43',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "NEW BEETLE '99->'02",
        Value: '44',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "LUPO '99->",
        Value: '45',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AUDI TT COUPE/ROADST',
        Value: '46',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "BORA/VARIANT '99->'0",
        Value: '47',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "LUPO 3L '99->",
        Value: '48',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A2 '2000->",
        Value: '49',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A4 '01->/AVANT ",
        Value: '50',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI CABRIOLET '03->",
        Value: '51',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A8 '03->",
        Value: '52',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 100->'76",
        Value: '53',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI A3 '04->/SPORTB",
        Value: '54',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 100/200 '77->'8",
        Value: '55',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 80 ->'78",
        Value: '56',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "AUDI 100 '83->'90",
        Value: '57',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PHAETON '02->",
        Value: '58',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "TOUAREG '03->",
        Value: '59',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'sportback mod 20',
        Value: '5G',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'N.B. CABRIO 03<10',
        Value: '60',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "TOURAN '03->",
        Value: '61',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "T5 KASTEN '04->",
        Value: '62',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "T5 KOMBI/MULTIVAN '0",
        Value: '63',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "T5 PRITSCHE '04->",
        Value: '64',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "T5 DOKA '04->",
        Value: '65',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "T5 CAMPER '04->",
        Value: '66',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Golf<09',
        Value: '68',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "CADDY'04->",
        Value: '69',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911/76-89',
        Value: '70',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911 T/75-89',
        Value: '71',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 924/76-85',
        Value: '72',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 928/S 76-85',
        Value: '73',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 924 TURBO',
        Value: '74',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 944/S 82-91',
        Value: '75',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 944 TURBO',
        Value: '76',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 924S/86-88',
        Value: '77',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 928S4,GT,GTS',
        Value: '78',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911C4',
        Value: '79',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BOXSTER',
        Value: '7A',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PO 911 C2 (996)',
        Value: '7B',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PO 911 C4 (996)',
        Value: '7C',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PO 911 GT3 (996)',
        Value: '7D',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'CAYENNE >03',
        Value: '7E',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'CARRERA GT (980)',
        Value: '7F',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BOXSTER (987)',
        Value: '7G',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PO CARRERA 997',
        Value: '7H',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'CAYENNE >07',
        Value: '7J',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911C2',
        Value: '80',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911 T.91-93',
        Value: '81',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 968',
        Value: '82',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911',
        Value: '83',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'CARRERA 4',
        Value: '84',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Porsche 911/TURBO/95',
        Value: '85',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Felicia',
        Value: '96',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Octavia',
        Value: '97',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Favorit',
        Value: '98',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Golf 1',
        Value: '99',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Fabia',
        Value: '9A',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Superb',
        Value: '9B',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Octavia II (Nachfolg',
        Value: '9C',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Roomster',
        Value: '9D',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '123456',
        Value: '9O',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'AA',
        Value: 'AA',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Fox03>09',
        Value: 'B1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GOL/PINTER MOD.99>02',
        Value: 'B2',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PARATI/POIN:MOD99>02',
        Value: 'B3',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'SAVEIRO/POINT 99>05',
        Value: 'B4',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'POLO HAT/MOD.02>',
        Value: 'B5',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GOLF A4 MOD.>99',
        Value: 'B6',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'SANATAN MOD.98>',
        Value: 'B7',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'KOMBI T2 FURGAO 99>',
        Value: 'B8',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GOL/POINTER MOD.>06',
        Value: 'B9',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PARATI/POINTER SW/GO',
        Value: 'BA',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'SAVEIRO/PINTER PICK',
        Value: 'BB',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'SURAN/SPACE/SPORT06>',
        Value: 'BC',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Fox/Voyage 83>96',
        Value: 'BD',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GOL/VOY./SAV.>09',
        Value: 'BE',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Saveiro>09',
        Value: 'BF',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Suran>11',
        Value: 'BG',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Fox>10',
        Value: 'BH',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: 'BI',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: 'BJ',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: 'BK',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY CONT. GT 04>11',
        Value: 'E1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY CONT. FS 05>',
        Value: 'E2',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY CONT. GTC 07>12',
        Value: 'E3',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY CONT. NEW GTC 12>',
        Value: 'E4',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: 'E5',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY ARNAGE 98>',
        Value: 'E6',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY AZURE 06>',
        Value: 'E7',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY BROOKLANDS 09>',
        Value: 'E8',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Veyron>06',
        Value: 'E9',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY LEGACY >02',
        Value: 'EA',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'SUPERSPORTS GT 10>',
        Value: 'EB',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'SUPERSPORTS GTC 11>',
        Value: 'EC',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY MULSANNE 11>',
        Value: 'ED',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BY CONT. NEW GT 11>',
        Value: 'EE',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Bus&Trucks Brasilien',
        Value: 'F1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'PoloG>10',
        Value: 'I1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "JETTA/BORA '05->",
        Value: 'M1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GO/JET/SP:V/>06',
        Value: 'M2',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'GO/JET/BO-Variant>10',
        Value: 'M3',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'JETAA>11',
        Value: 'M4',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: 'M5',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'BEETLE CABRIO >12',
        Value: 'M6',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '12345678',
        Value: 'MB',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'TYP1',
        Value: 'O1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'TYP2',
        Value: 'O2',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'TYP3',
        Value: 'O3',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'VW 411',
        Value: 'O4',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'VW K70',
        Value: 'O5',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "PASSAT ->'80",
        Value: 'O6',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "GOLF ->'83",
        Value: 'O8',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "POLO/DERBY ->'81",
        Value: 'O9',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Peugeot',
        Value: 'PE',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Polo>11',
        Value: 'R1',
    },
    {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: '',
        Value: 'X2',
    },
];

export const obj2:Obj2Type[] = [
    {
        bEdvTyp: '**',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '00',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '01',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '02',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '03',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '04',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '05',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '06',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '08',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '09',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '10',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '11',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '12',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '13',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '14',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '15',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '16',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '17',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '18',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '19',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1A',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1B',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1C',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1D',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1E',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1F',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1G',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1H',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1I',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1J',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1K',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1L',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1M',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1N',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1O',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1P',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1Q',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1R',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1S',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1T',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1V',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '1X',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '20',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '21',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '22',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '23',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '24',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '25',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '26',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '27',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '28',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '29',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2A',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2B',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2C',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2D',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2E',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2F',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2G',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2H',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2I',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2J',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2K',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2L',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2M',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2N',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2O',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2P',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '2Q',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '30',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '31',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '32',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '33',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '34',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '35',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '36',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '37',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '38',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '39',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '3A',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '3B',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '3C',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '3D',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '3E',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '40',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '41',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '42',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '43',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '44',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '45',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '46',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '47',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '48',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '49',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '50',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '51',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '52',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '53',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '54',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '55',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '56',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '57',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '58',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '59',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '5G',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '60',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '61',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '62',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '63',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '64',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '65',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '66',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '68',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '69',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '70',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '71',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '72',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '73',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '74',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '75',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '76',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '77',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '78',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '79',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7A',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7B',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7C',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7D',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7E',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7F',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7G',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7H',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '7J',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '80',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '81',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '82',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '83',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '84',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '85',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '96',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '97',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '98',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '99',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '9A',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '9B',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '9C',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '9D',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: '9O',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'AA',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B2',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B3',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B4',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B5',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B6',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B7',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B8',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'B9',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BA',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BB',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BC',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BD',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BE',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BF',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BG',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BH',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BI',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BJ',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'BK',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E2',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E3',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E4',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E5',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E6',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E7',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E8',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'E9',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'EA',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'EB',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'EC',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'ED',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'EE',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'F1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'I1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'M1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'M2',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'M3',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'M4',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'M5',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'M6',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'MB',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O2',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O3',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O4',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O5',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O6',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O8',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'O9',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'PE',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'R1',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
    {
        bEdvTyp: 'X2',
        bKzLackMaterial: ' ',
        dZEArbeitsWert: 0.21,
        dPreis: 0.0,
        dZeVs5: 0.0,
        bVs5Cha: false,
        lMaterialEinheiten: 0,
    },
];